### ISSUE TITLE
Invalid query doesn't raise exception

### ISSUE THREAD

**Issue by dmachi** [pjwerneck/pyrql#10]
This query, structured properly works: 

```
>>> parsed = pyrql.parse("in(foo,(foo,bar))&sort(+foo)&eq(userid,user)")
>>> parsed
{'name': 'and', 'args': [{'name': 'in', 'args': ['foo', ('foo', 'bar')]}, {'name': 'sort', 'args': [('+', 'foo')]}, {'name': 'eq', 'args': ['userid', 'user']}]}
```
However, if there is an extra paranthesis in the query such as:

`"in(foo,(foo,bar))&sort(+foo))&eq(userid,user)"`

Instead of throwing an error, it just ignores the rest of the query making it unsafe to use when appending query elements to sanitize user provided queries.

```
>>> parsed = pyrql.parse("in(foo,(foo,bar))&sort(+foo))&eq(userid,user)")
>>> parsed
{'name': 'and', 'args': [{'name': 'in', 'args': ['foo', ('foo', 'bar')]}, {'name': 'sort', 'args': [('+', 'foo')]}]}
```

Is there any quick/easy fix for this?

**Comment by pjwerneck** [comment]
@dmachi Good catch. I always assumed pyparsing did proper balance checks. Maybe it can be fixed through the grammar, maybe it needs some pre/post processing. I'll look into that.
